# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'greenhouse-ver-02' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for greenhouse-ver-02
 pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'

  target 'greenhouse-ver-02Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'greenhouse-ver-02UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
